spring.application.name=backend
# ===============================
# SERVER
# ===============================
server.port=8080


# ===============================
# DATABASE CONFIG (RENDER)
# ===============================
spring.datasource.url=jdbc:postgresql://dpg-d6as67vgi27c73d9qvq0-a.oregon-postgres.render.com:5432/bitlab_db
spring.datasource.username=bitlab_db_user
spring.datasource.password=AQu7E9TRGlHun08HxCUFRHCDI7WgSfQv
spring.datasource.driver-class-name=org.postgresql.Driver


# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


# ===============================
# FILE UPLOAD LIMITS
# ===============================
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB


# ===============================
# SESSION
# ===============================
server.servlet.session.timeout=30m


# ===============================
# LOGGING
# ===============================
logging.level.org.springframework.security=INFO
logging.level.org.hibernate.SQL=DEBUG


# ===============================
# BITLAB CUSTOM CONFIG
# ===============================
bitlab.workspace-root=./workspace
bitlab.execution-timeout-seconds=10